# Generated by Django 4.2.17 on 2024-12-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
