# Generated by Django 4.2.17 on 2024-12-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notes_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='in_bin',
            field=models.BooleanField(default=False),
        ),
    ]
