# Generated by Django 4.2.17 on 2024-12-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notes_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='username',
            new_name='user',
        ),
    ]
