# Generated by Django 4.2.17 on 2024-12-22 16:26

from django.db import migrations, models
import uuid

def generate_unique_uuids(apps, schema_editor):
    Notes = apps.get_model('app', 'Notes')  
    for note in Notes.objects.filter(share_uuid__isnull=True):
        note.share_uuid = uuid.uuid4()
        note.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_username_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True),  # Add the field
        ),
        migrations.RunPython(generate_unique_uuids),  # Populate existing rows with UUIDs

        migrations.AlterField(
            model_name='notes',
            name='share_uuid',
            field=models.UUIDField(editable=False, unique=True),  # Make the field non-nullable after population
        ),
    ]

