# Generated by Django 4.2.17 on 2024-12-23 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notes_share_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
